### ISSUE TITLE
App link

### ISSUE THREAD

**Issue by philipvollet** [janskwr/Russia-Ukraine-Twitter-Analysis#2]
not sure if you really want to link to this YouTube video: https://www.youtube.com/watch?v=-KQpq4-2Qdk or if this is just a placeholder

**Comment by janskwr** [comment]
It's just a placeholder - I've created this beta README yesterday. There are some optimization issues with Streamlit app and proper link will probably be available in 2 days. I will let you know here (not closing this Issue yet). Sorry for the inconvenience.

**Comment by janskwr** [comment]
@philipvollet 
The link is working now. Please note that this is a beta version (there are still some optimization issues, it's working only on 3% of our data). If you have any questions, please do not hesitate to contact me. Any feedback would be greatly appreciated!
